# PostionTeller v1.1 - Settings.yml Configeration file
settings:
    general:
        
    messages:
        showpos:
            format: "&6X: &l&b@x&r &6Y: &l&b@y&r &6Z: &l&b@z"
        togglepos:
            self:
                succeed:
                    activate: "&aYou have activated PositionTeller!"
                    de-activate: "&6You have de-activated PositionTeller!"
                fail:
                    default: "&cPositionTeller couldn't be activated."
                    permission: "&cYou do not have permissions to use this command!"
                    game: "&cPlease run this command in-game!"
            other:
                succeed:
                    activate:
                        sender: "&aYou have activated PostionTeller for &l&b@reciver&r&a!"
                        reciver: "&l&b@sender&r &ahas activated PositionTeller for you!"
                    de-activate:
                        sender: "&aPositionTeller has been de-activated for &l&b@reciver&r&a!"
                        reciver: "&l&b@sender&r &ahas de-activated PositionTeller for you!"
                fail:
                        default: "&cPositionTeller couldn't find a player named &l&b@reciver&r&a, make sure you type a valid players name."
                        permission: "&cYou do not have permissions to use this command!"