#MoreCommands v1.0 Config File
#
#/Spawn Command
Spawn-Command-Enabled: true
#/Spawn Command Message. Use \n for a new line
Teleport-to-Spawn-Message: "----------------------------------------\nTeleporting to Spawn\n----------------------------------------"
#
#/Hub Command
Hub-Command-Enabled: true
#/Hub Command Message. Use \n for a new line
Teleport-to-Hub-Message: "----------------------------------------\nTeleporting to Hub\n----------------------------------------"
#
#/Lobby Command
Lobby-Command-Enabled: true
#/Lobby Command Message. Use \n for a new line
Teleport-to-Lobby-Message: "----------------------------------------\nTeleporting to Lobby\n----------------------------------------"
