name: WorldProtector
author: CrazedMiner
description: Protects your worlds
version: 1.0
main: CrazedMiner/Main
website: CrazedMiner.weebly.com
api: 1.4.1

permissions:
    worldprotector:
        description: Main permission node for all
        default: op
        
        worldprotector.block:
            description: Main permission node for block things
            default: op
            
            worldprotector.block.break:
                description: Permission node that disables block breaking
                default: op
            worldprotector.block.place:
                description: Permission node that disables block placing
                default: op
