name: PvP-Stats
author: Jack Noordhuis (CrazedMiner)
version: 1.1
description: Counts players kills and deaths.
main: CrazedMiner\Main
api: [1.12.0]

commands:
    stats:
        description: "Checks a players stats."
        
permissions:
    pvp-stats.command.other:
        description: Players with this permission are able to check the stats of other Players.
        default: op
        
    pvp-stats.command.self:
        description: Players with this permission are able to clear their own Inventories.
        default: true
