name: Sneak
author: CrazedMiner
version: 1.1
description: Players can Sneak by simply using a Command!
main: Sneak\Main
api: [1.12.0]

commands:
    sneak:
        description: "Toggles Sneaking for you or the specified Player"

permissions:
    sneak.command.other:
        description: Players with this permission are able to toggle sneaking for other Players
        default: op
            
    sneak.command.self:
        description: Players with this permission are able to toggle Sneaking for themselves
        default: true
